GET http://localhost:3001/login

###

GET http://localhost:3001/logout

###

GET http://localhost:3001/register

###

GET http://localhost:3001/profile

###

GET http://localhost:3001/getUser

###
POST http://localhost:3001/login
[
{
"username": "admin", "password": "admin" 
}
]

###
POST http://localhost:3001/register

[
{
"username": "admin1", "password": "admin1" 
}
]